language: node_js
sudo: required
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "4.1" 
  - "5.4" 
  - "iojs" .. breaks on serialport
script: make test-cov-travis
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
